name = "auth-svc"
main = "src/index.ts"
compatibility_date = "2025-03-15"

[vars]
JWT_ISSUER = "assessment-platform"
ACCESS_TOKEN_EXPIRY = "900"
REFRESH_TOKEN_EXPIRY = "604800"

[[kv_namespaces]]
binding = "KV"
id = "d298e7708ad44a25b6dfb8eab8249b84"

[env.production]
name = "auth-svc-production"

[[env.production.kv_namespaces]]
binding = "KV"
id = "d298e7708ad44a25b6dfb8eab8249b84"